# -------------------------------------------------------------------------------------
#
# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

name: Asgardeo Login Playground
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/package.json'

      # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.3
        with:
          token: ${{ secrets.ASGARDEO_LOGIN_PLAYGROUND_TOKEN }}
      - name: Build and Release version
        env:
          ACCESS_TOKEN: ${{ secrets.ASGARDEO_LOGIN_PLAYGROUND_TOKEN }}
        run: bash release-artifacts.sh $GITHUB_WORKSPACE $ACCESS_TOKEN

